

var NOMBREusuario=prompt("INGRESA TU NOMBRE PARA PARTICIPAR DE FERIA TECNOINNOVA2022")
var EDADusuario=prompt("INGRESA TU EDAD")
var DNIusuario=prompt("INGRESA TU DNI")
var MAILusuario=prompt("INGRESA POR ULTIMO TU MAIL")
var CONCURSANTE=3 //COLOCO UNA CANTIDAD ARBRITARIA DE CONCURSANTES


prompt("INGRESA OK PARA CONFIRMAR TUS DATOS " 
		+  NOMBREusuario + " " +EDADusuario +" "+ DNIusuario+" " +MAILusuario)

CONCURSANTE=CONCURSANTE +1

alert("¡FELICIDADES " +  NOMBREusuario + " YA ESTAS PARTICIPANDO POR EL SORTEO DE UNA ENTRADA PARA LA FERIA!")


